### ISSUE TITLE
Support other source formats like json?

### ISSUE THREAD

**Issue by ttasanen** [byroot/frozen_record#11]
Do you have any plans to support other source formats than YAML? This nice little gem does exactly what I need, but now I just have to convert json files to yaml in my current project. 

I was looking at the source and seems it would be pretty easy to add support for other source formats as well.. 

I would not tie this strictly to yaml and json, but maybe allow user to pass a `proc` that could return any `Enumerable` with the data? But still defaulting to `YAML.load_file`

If you are interested I could hack something together and submit a PR?

**Comment by byroot** [comment]
Sure why not. That being said, one nice thing with YAML is that it's a super set of JSON. So you could simply feed JSON files to frozen_record without any modification (unless I'm missing something?).

**Comment by bernardoamc** [comment]
I think we can close this one based on #20
