### ISSUE TITLE
YAML undefined using bundler ~> 1.11.1 

### ISSUE THREAD

**Issue by sbfaulkner** [byroot/frozen_record#13]
bundler 1.11.1 started lazy-loading Psych (https://github.com/bundler/bundler/blob/master/CHANGELOG.md#1111-2015-12-15)

the result is that it's now possible for YAML to not be defined when attempting to use frozen_record

the work-around is to `require 'yaml'` in the consuming project

I *think* the more correct fix is to `require 'yaml'` in lib/frozen_record/base.rb

/cc @mattvleming @byroot

**Comment by byroot** [comment]
Released as `0.5.1`

**Comment by sbfaulkner** [comment]
you're awesome @byroot ... you'd shipped this faster than we shipped our work-around :dash:
