### ISSUE TITLE
[Discussion] API to declare a prefiltered scope.

### ISSUE THREAD

**Issue by bernardoamc** [byroot/frozen_record#14]
Let me start with the current use case and how we are dealing with different scopes.

Right now we have a model and we want to search records from this model in two distinct ways. To make this more clear here is the way we are doing it:

```ruby
def MyClass
  def self.search(search_term)
    PrefixSearchScope.new(self).search(search_term)
  end

  def self.prefix_search
    @prefix_search ||= PrefixSearch.new(all, fields: [:label])
  end

  class PrefixSearchScope < FrozenRecord::Scope
    def initialize(*)
      @search_term = nil
      super
    end

    def search!(search_term)
      @search_term = search_term
      self
    end

    def search(search_term)
      spawn.search!(search_term)
    end

    protected

    def select_records(records)
      if @search_term.present?
        super(@klass.prefix_search.find(@search_term))
      else
        super(records)
      end
    end
  end
end
```

It would be interesting to be able to declare something like `.with_scoped_subset` in our class  that returns a `FrozenRecord::Scope` for a predefined set of records instead of calling `.load_records`. 

Example:

```ruby
def self.with_scoped_subset(subset)
  # Returns a `FrozenRecord::Scope` over `subset`
end

def self.search(search_term)
  search_results = prefix_search.find(search_term)
  with_scoped_subset(search_results)
end
```

**Comment by casperisfine** [comment]
Sorry but I don't understand how that is different from a regular scope.

**Comment by davidcornu** [comment]
Say I have `[1,2,3,4]` in my YAML file and I want to write a method that only returns odd numbers:

```ruby
def self.odd
  all.reject(&:even?)
end
```

That method returns a standard `Array` which can't be further filtered like a regular `Scope`.

Right now we're accomplishing this by returning a subclass of `Scope` but that's pretty tedious. What we're suggesting is having a way to something like

```ruby
def self.odd
  FrozenRecord::Scope.new(self, all.reject(&:even?))
end
```

**Comment by casperisfine** [comment]
I see.

I'd rather support `where { |i| i.odd? }`, would that work for you?

**Comment by davidcornu** [comment]
I used `odd` as an example but in our case we're returning an ordered set of results. `where { |i| i.odd? }` would mean we'd have to filter by inclusion in a set and probably add an equivalent `sort`.

We may also be doing something uncommon enough that doesn't warrant inclusion in the gem 😛

**Comment by casperisfine** [comment]
> We may also be doing something uncommon enough that doesn't warrant inclusion in the gem

I believe so yes.

Unless you can point out a similar API in Active Record, but I don't know about such thing.
