### ISSUE TITLE
[Enhancement] Forcing a reload of records 

### ISSUE THREAD

**Issue by robinbrandt** [byroot/frozen_record#15]
I recently wanted to write a test for a FrozenRecord model that uses different fixtures (and therefore different backing YAML files) in tests than in production. This was harder than I'd like it to be and it forced me to set an instance variable from the outside to force `FrozenRecord` to reload the records. 

In my test class:
```
class MyModelTest < ActiveSupport::TestCase
  test ".complicated_finder_method does something" do
    with_test_data do
      assert_equal 1, MyModel.complicated_finder_method(...).size
    end
  end

  def with_test_data(name)
      MyModel.stubs(:file_path).returns(Rails.root.join('test/files/data/#{name}.yml'))
      # need to reset the records to force it to read the file again
      MyModel.instance_variable_set(:@records, nil)
      MyModel.load_records
      yield
    ensure
      MyModel.unstub(:file_path)
      MyModel.instance_variable_set(:@records, nil)
      MyModel.load_records
    end
end
```

I can live with stubbing the public `file_path` method but I don't like the `MyModel.instance_variable_set(:@records, nil)`. Any chance we could get support for this use case into FrozenRecord?

**Comment by casperisfine** [comment]
To be honest I'm a bit uncomfortable with this, as it would too easily lead to global state leak between requests etc.

Would subclassing for test purpose work for you?

```ruby
class MyModelTest < ActiveSupport::TestCase
  class MyTestModel < MyModel
    def self.file_path
      Rails.root.join('test/files/data/blah.yml')
    end
  end

  test ".complicated_finder_method does something" do
    with_test_data do
      assert_equal 1, MyTestModel.complicated_finder_method(...).size
    end
  end
end
```

**Comment by robinbrandt** [comment]
Sounds fine. Thanks.

**Comment by byroot** [comment]
https://github.com/byroot/frozen_record/pull/24 made all this easier a while ago. Closing.
