### ISSUE TITLE
Can an ActiveRecord reference a FrozenRecord?

### ISSUE THREAD

**Issue by jimeng** [byroot/frozen_record#17]
Suppose you use FrozenRecord to define a class named Department with 12 instances, each with a unique "id".  Then you want the class Person to belong_to a Department.  Is that possible?  

If so, can you show an example of the syntax in the two classes to make that happen?

If not, is that on your roadmap?

**Comment by byroot** [comment]
It's not supported, I think adding transparent support for it would be quite complicated.

What we usually do is this:

```
class Person < AR::Base
  def department
    Department.find(department_id) if department_id?
  end

  def department=(dep)
    self.department_id = dep ? dep.id : nil
  end

end

class Department < FrozenRecord::Base
  def people
    Person.where(department_id: id)
  end
end
```

It's not 100% consistent with real Active Record associations, but it's close enough that it's mostly not an issue.

Hope it helps, feel free to reopen if you have further questions.
