### ISSUE TITLE
Incompatible with Ruby 2.5

### ISSUE THREAD

**Issue by brendo** [byroot/frozen_record#35]
The introduction of indexing in 0.19.0 has resulted in CI failing for Ruby 2.5:

![Screen Shot 2020-08-06 at 11 34 34 am](https://user-images.githubusercontent.com/69268/89480493-d2564b80-d7d8-11ea-9f30-b4a3cd9ac456.jpg)

The [error](https://travis-ci.org/github/byroot/frozen_record/jobs/708638331) is:

![Screen Shot 2020-08-06 at 11 35 20 am](https://user-images.githubusercontent.com/69268/89480527-f2860a80-d7d8-11ea-9365-0b97fce5c8f9.jpg)

**Comment by casperisfine** [comment]
Ouch, what an oversight, thanks!
