### ISSUE TITLE
Frozen record failing for activerecord version 5

### ISSUE THREAD

**Issue by rramsden** [byroot/frozen_record#36]
## Context

May be a duplicate of https://github.com/byroot/frozen_record/issues/35 but since 0.19.0 and introduction of indexing we have tests failing after updating to the latest version (see https://github.com/activemerchant/payment_icons/pull/301)

I've created a repository to show the failing behavior
https://github.com/rramsden/frozen-record-bug

**Comment by casperisfine** [comment]
Thanks for letting me know, it's now fixed in `0.19.2`.
