### ISSUE TITLE
Acceptable use cases?

### ISSUE THREAD

**Issue by beauraF** [byroot/frozen_record#46]
Hi @byroot,

Thanks a lot for your work. 💪

We also use a notion of `FrozenRecord` at my work, but I have a hard time figuring out when to use them, when not and providing clear guidelines.
I would be very interested in your opinion on this, if you have some time to spare.

Thanks in advance!

**Comment by casperisfine** [comment]
I never really thought about guidelines. It's more of a matter of tradeoffs IMO.

Frozen Record dbs are managed with your code. Which mean they are versioned in git, revertable, easily testable on CI etc. So it's good for datasets such as customer plans etc that are somewhat part of the logic of your app and are not constantly updated. 

On the other hand they increase the memory usage of the app, don't have a particularly good query performance on large datasets and/or complex queries. So it only suits reasonably small datasets.

I hope this helps.

**Comment by beauraF** [comment]
Thanks for the quick answer ! Yep, definitely. 

> I never really thought about guidelines. It's more of a matter of tradeoffs IMO.

I completely agree. But I try to put these tradeoffs on paper, with a "Rule Of Thumb" or something like that.

I find them so dangerous in terms of data integrity, that I encourage their use only when you need to keep the code synchronized with one of the record values.

Example:
```ruby
# capabilities.yml
- id: 1
  name: staff_account_create
  description: can create a staff account

Current.account.capable_of?("staff_account_create")
```

But you are right, if the data never change, like a list of country, the data integrity risk is null, even if they are linked to many other records.

Anyway, thanks a lot @byroot. I come back to you if I can get something right out of this. You might be interested to put it in the README.
