### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by sandstrom** [byroot/frozen_record#55]
This is a stable and popular project. I'd recommend signaling that, by releasing 1.0! 

![image](https://user-images.githubusercontent.com/122287/174795091-c601919d-3eec-45b8-9825-2a51f344dc08.png)

**Comment by byroot** [comment]
Thank you for the suggestion, but I don't plan to do such thing. Versions are just a monotonically increasing number anyway, I don't claim semver or anything like that.

**Comment by sandstrom** [comment]
@byroot that is true, but not everyone sees it that way :) You don't have to claim semver, you could just arbitrarily bump it 😄 

Anyway, great gem! 🏅
